import type { ToolbarItemId } from '../core/types';

type LabelKey = Exclude<ToolbarItemId, 'divider' | 'group'>;

export const TOOLBAR_LABELS: Record<LabelKey, string> = {
  undo: '↶',
  redo: '↷',
  painter: '🖌',
  eraser: '⌫',
  heading: 'H',
  heading1: 'H1',
  heading2: 'H2',
  heading3: 'H3',
  heading4: 'H4',
  heading5: 'H5',
  heading6: 'H6',
  paragraph: '¶',
  fontSize: 'A↕',
  fontFamily: 'Aa',
  bold: 'B',
  italic: 'I',
  underline: 'U',
  strike: 'S',
  strikethrough: 'S',
  code: '`',
  highlight: '🖍',
  fontColor: 'A',
  subscript: 'X₂',
  superscript: 'X²',
  align: '≡',
  alignLeft: '☰',
  alignCenter: '☰',
  alignRight: '☰',
  alignJustify: '☰',
  lineHeight: '↕',
  bulletList: '•',
  orderedList: '1.',
  numberedList: '1.',
  todo: '☑',
  indentDecrease: '⇤',
  indentIncrease: '⇥',
  quote: '❝',
  codeBlock: '</>',
  container: '▢',
  link: '🔗',
  image: '🖼',
  attachment: '📎',
  table: '▦',
  tableCellBackgroundColor: '▦🎨',
  hr: '—',
  break: '↵',
  emoji: '😀',
  custom: '★',
  sourceCode: '</>',
  fullscreen: '⛶',
  printer: '🖨',
};

export const TOOLBAR_TITLES: Record<LabelKey, string> = {
  undo: 'Undo',
  redo: 'Redo',
  painter: 'Format painter',
  eraser: 'Clear formatting',
  heading: 'Heading',
  heading1: 'Heading 1',
  heading2: 'Heading 2',
  heading3: 'Heading 3',
  heading4: 'Heading 4',
  heading5: 'Heading 5',
  heading6: 'Heading 6',
  paragraph: 'Paragraph',
  fontSize: 'Font size',
  fontFamily: 'Font family',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  strike: 'Strikethrough',
  strikethrough: 'Strikethrough',
  code: 'Inline code',
  highlight: 'Highlight',
  fontColor: 'Font color',
  subscript: 'Subscript',
  superscript: 'Superscript',
  align: 'Align',
  alignLeft: 'Align left',
  alignCenter: 'Align center',
  alignRight: 'Align right',
  alignJustify: 'Justify',
  lineHeight: 'Line height',
  bulletList: 'Bulleted list',
  orderedList: 'Ordered list',
  numberedList: 'Ordered list',
  todo: 'To-do list',
  indentDecrease: 'Decrease indent',
  indentIncrease: 'Increase indent',
  quote: 'Quote',
  codeBlock: 'Code block',
  container: 'Container',
  link: 'Link',
  image: 'Image',
  attachment: 'Attachment',
  table: 'Insert table',
  tableCellBackgroundColor: 'Cell background',
  hr: 'Horizontal rule',
  break: 'Line break',
  emoji: 'Emoji',
  custom: 'Custom action',
  sourceCode: 'Source code',
  fullscreen: 'Fullscreen',
  printer: 'Print',
};

export const FONT_SIZES = ['12px', '13px', '14px', '15px', '16px', '18px', '20px', '24px', '28px', '32px', '36px', '48px'];

export const FONT_FAMILIES = [
  { label: 'Default', value: '' },
  { label: 'Sans Serif', value: 'ui-sans-serif, system-ui, sans-serif' },
  { label: 'Serif', value: 'ui-serif, Georgia, serif' },
  { label: 'Monospace', value: 'ui-monospace, SFMono-Regular, Menlo, monospace' },
  { label: 'Arial', value: 'Arial, Helvetica, sans-serif' },
  { label: 'Times New Roman', value: '"Times New Roman", Times, serif' },
  { label: 'Courier New', value: '"Courier New", Courier, monospace' },
];

export const LINE_HEIGHTS = ['1', '1.15', '1.5', '1.75', '2', '2.5', '3'];

export const FONT_COLORS = [
  '#000000', '#434343', '#666666', '#999999', '#cccccc', '#ffffff',
  '#e60000', '#f08800', '#ffff00', '#008a00', '#0066cc', '#9933ff',
  '#facccc', '#ffebcc', '#ffffcc', '#cce8cc', '#cce0f5', '#ebd6ff',
];

export const BG_COLORS = [
  'transparent', '#ffff00', '#00ff00', '#00ffff', '#ff00ff', '#0000ff',
  '#ff0000', '#000080', '#008080', '#800080', '#800000', '#808000',
  '#c0c0c0', '#808080', '#9999ff', '#993366', '#ffffcc', '#ccffff',
];

export const EMOJI_LIST = [
  '😀', '😁', '😂', '🤣', '😃', '😄', '😅', '😆', '😉', '😊',
  '😋', '😎', '😍', '😘', '🥰', '😗', '😙', '🥲', '🤔', '🤨',
  '😐', '😑', '😶', '🙄', '😏', '😣', '😥', '😮', '🤐', '😯',
  '😪', '😫', '🥱', '😴', '😌', '😛', '😜', '😝', '🤤', '😒',
  '😓', '😔', '😕', '🙃', '🤑', '😲', '☹️', '🙁', '😖', '😞',
  '👍', '👎', '👏', '🙌', '🤝', '🙏', '💪', '✨', '🔥', '💯',
  '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '💔', '❣️',
  '✅', '❌', '⭐', '🌟', '💡', '📌', '📎', '🔗', '📝', '🎉',
];
