import type { UniEditorTheme } from './types';

export const defaultTheme: UniEditorTheme = {
  paragraph: 'uni-paragraph',
  quote: 'uni-quote',
  heading: {
    h1: 'uni-h1',
    h2: 'uni-h2',
    h3: 'uni-h3',
    h4: 'uni-h4',
    h5: 'uni-h5',
    h6: 'uni-h6',
  },
  list: {
    ul: 'uni-ul',
    ol: 'uni-ol',
    listitem: 'uni-li',
    nested: {
      listitem: 'uni-nested-li',
    },
    listitemChecked: 'uni-li-checked',
    listitemUnchecked: 'uni-li-unchecked',
    checklist: 'uni-checklist',
  },
  link: 'uni-link',
  text: {
    bold: 'uni-text-bold',
    italic: 'uni-text-italic',
    underline: 'uni-text-underline',
    strikethrough: 'uni-text-strikethrough',
    underlineStrikethrough: 'uni-text-underline-strikethrough',
    code: 'uni-text-code',
    highlight: 'uni-text-highlight',
    subscript: 'uni-text-subscript',
    superscript: 'uni-text-superscript',
  },
  table: 'uni-table',
  tableCell: 'uni-table-cell',
  tableCellHeader: 'uni-table-cell-header',
  tableRow: 'uni-table-row',
  code: 'uni-code-block',
  codeHighlight: {
    atrule: 'uni-token-atrule',
    attr: 'uni-token-attr',
    boolean: 'uni-token-boolean',
    builtin: 'uni-token-builtin',
    cdata: 'uni-token-cdata',
    char: 'uni-token-char',
    class: 'uni-token-class',
    'class-name': 'uni-token-class-name',
    comment: 'uni-token-comment',
    constant: 'uni-token-constant',
    deleted: 'uni-token-deleted',
    doctype: 'uni-token-doctype',
    entity: 'uni-token-entity',
    function: 'uni-token-function',
    important: 'uni-token-important',
    inserted: 'uni-token-inserted',
    keyword: 'uni-token-keyword',
    namespace: 'uni-token-namespace',
    number: 'uni-token-number',
    operator: 'uni-token-operator',
    prolog: 'uni-token-prolog',
    property: 'uni-token-property',
    punctuation: 'uni-token-punctuation',
    regex: 'uni-token-regex',
    selector: 'uni-token-selector',
    string: 'uni-token-string',
    symbol: 'uni-token-symbol',
    tag: 'uni-token-tag',
    url: 'uni-token-url',
    variable: 'uni-token-variable',
  },
  blockWrapper: 'uni-block-wrapper',
  image: 'uni-image',
  imageLoading: 'uni-image-loading',
  slashMenu: 'uni-slash-menu',
  slashMenuItem: 'uni-slash-menu-item',
  slashMenuItemActive: 'uni-slash-menu-item-active',
  blockOverlay: 'uni-block-overlay',
  dragHandle: 'uni-drag-handle',
  plusButton: 'uni-plus-button',
  toolbar: 'uni-toolbar',
  toolbarButton: 'uni-toolbar-btn',
  toolbarButtonActive: 'uni-toolbar-btn-active',
  toolbarDivider: 'uni-toolbar-divider',
  hr: 'uni-hr',
  attachment: 'uni-attachment',
  container: 'uni-container',
  toggle: 'uni-toggle',
  datetime: 'uni-datetime',
  todoChecked: 'uni-li-checked',
  todoUnchecked: 'uni-li-unchecked',
};
